server:
  port: 8096

app:
  id: 68080b07-7422-4b65-932a-65c4988e0e82
  aop:
    time-tracking-enabled: true

storage:
  binary:
    read:
      chunk-size: 1024

aws:
  s3:
    access-key: CHANGEME
    secret-key: CHANGEME

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/diffs
    username: root
    password: waes_mysql
  jpa:
    hibernate.ddl-auto: create-drop
    show-sql: false
    properties.hibernate.format_sql: true

logging:
  level:
    root: INFO
    org:
      hibernate: ERROR

springdoc:
  paths-to-match: /v1/diff/**
  api-docs.path: /api-docs
  swagger-ui:
    path: /api-docs-ui