server:
  port: 8096

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/diffstest
    username: root
    password: waes_mysql
  jpa:
    hibernate.ddl-auto: create-drop
    show-sql: false
    properties.hibernate.format_sql: true
  profiles:
    active: test

logging:
  level:
    root: INFO
    org:
      hibernate: ERROR